name: Build and Package Applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Remove node_modules
        run: rm -rf node_modules pacakge-lock.json
        working-directory: ./electron

      - name: Install dependencies
        run: npm install --no-optional
        working-directory: ./electron
      
      - name: Install npm-check-updates
        run: npm install -g npm-check-updates
        working-directory: ./electron

      - name: Update dependencies
        run: ncu -u
        working-directory: ./electron

      - name: Install updated dependencies
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            npm install --no-optional
          else
            npm install --ignore-scripts --no-optional
          fi
        shell: bash
        working-directory: ./electron
      

      - name: Build CSS
        run: npm run build-css
        working-directory: ./electron

      - name: Build Electron app for ${{ matrix.os }}
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            npm run dist
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run dist
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run dist
          fi
        shell: bash
        working-directory: ./electron

      - name: Upload Electron Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-dist-${{ matrix.os }}
          path: electron/dist/